/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "FreeRTOS.h"
#include "task.h"
#include <stdint.h>
#include "led.h"

// default clock configuration for stm32f407 DISCO board
uint32_t SystemCoreClock = 16000000;

static void vTaskBlinkGreen(void* pvParameters);
static void vTaskBlinkOrange(void* pvParameters);
static void vTaskBlinkBlue(void* pvParameters);

void vApplicationTickHook()
{

}

void vApplicationIdleHook()
{

}

void vApplicationMallocFailedHook()
{
	for(;;);
}

int main(void)
{

	BaseType_t xReturned;

	Init_LEDs();

	xReturned = xTaskCreate( vTaskBlinkGreen, "Led1", configMINIMAL_STACK_SIZE, ( void * ) NULL, tskIDLE_PRIORITY, NULL );
	if (xReturned != pdPASS)
	{
		while(1);
	}
	xReturned = xTaskCreate( vTaskBlinkOrange, "Led2", configMINIMAL_STACK_SIZE, ( void * ) NULL, tskIDLE_PRIORITY, NULL );
	if (xReturned != pdPASS)
	{
		while(1);
	}

	xReturned = xTaskCreate( vTaskBlinkBlue, "Led3", configMINIMAL_STACK_SIZE, ( void * ) NULL, tskIDLE_PRIORITY, NULL );
	if (xReturned != pdPASS)
	{
		while(1);
	}

	vTaskStartScheduler();

	/* Loop forever */
	for(;;);
}

void vTaskBlinkGreen(void* pvParameters)
{
	const TickType_t xDelay = 750 / portTICK_PERIOD_MS;

	for(;;)
	{
		GreenLED_On();
		vTaskDelay(xDelay);
		GreenLED_Off();
		vTaskDelay(xDelay);
	}
}

void vTaskBlinkOrange(void* pvParameters)
{
	const TickType_t xDelay = 1000 / portTICK_PERIOD_MS;

	for(;;)
	{
		OrangeLED_On();
		vTaskDelay(xDelay);
		OrangeLED_Off();
		vTaskDelay(xDelay);
	}
}

void vTaskBlinkBlue(void* pvParameters)
{
	const TickType_t xDelay = 500 / portTICK_PERIOD_MS;

	for(;;)
	{
		BlueLED_On();
		vTaskDelay(xDelay);
		BlueLED_Off();
		vTaskDelay(xDelay);
	}
}

